sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - TESTS_ZEND_AUTH_ADAPTER_DBTABLE_PDO_SQLITE_ENABLED=true
    - SITE_URL: https://zendframework.github.io/zend-authentication
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-authentication.git
    - secure: "EkN2Vnzdt2UUN740UtTsM5PzfEBIBPN4fhgjc0kFYGSVKPB/bvsKAMgMKLl7Q1+YrcncpjfuiXuPlhKQhe2zgNGMncBfcOKePgxVstuzHed19ssQK5g67gTChNcqI679RKaSpN1CQwf5y0bZ8qHEPtv3JBuBJT9osPqNlLUQ37kQPC8417EYfmiLi1JL04rHsvitX1rRYZgGV53vFtCdpvy4/w/Iy5NU1KkoiiwueMtR80SL15qRmFYBgBxi5jrW/IpwDCDT+SOX2ZaPHq6Jv4Qb8ndyFoswIJD0PBpB98QpyG+5t7ciTmZGO7xW+aLmpE4Ci38OMkzeoCXzyOLL6Li8+VstjUD2atJ0uNyl60benchapOZoHVT7Nm51fUaXAzjR+Q6XalF1lyExgeEZ56yM6NHBVwOWl+8Rly4xhP4v3u4vCwHQ/R6dZbAhcPkr3CgFr4ra31kDTfJHnVKlhDnNz3jtn/kBofmtMdRAknVLhTlTwAc2K4ZBgXMPz7bJvMDiCDh695vqChREKcsciH2B6Ad8q3C/mV/ior8errFZfupRvvP3fEXEgei0YSrigh1mzvFjZFYMMs52EkZ6qd8YtBRJLJxfBNAIatp/RW+urpPA7JtSdyff1fesyZQBAqbJhMfUXwYsj6OuQPjAZ6yB/6D9TjCufG+Mha/y+wo="
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CHECK_CS=true
    - php: 7
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - travis_retry composer self-update
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0 ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then travis_retry curl -sSL https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh | bash ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then ./zf-mkdoc-theme/deploy.sh ; fi
